services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stock_market
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
    ports:
      - "5432:5432"

  app1:
    build: .
    environment:
      DATABASE_URL: postgres://stock:stock@postgres:5432/stock_market?sslmode=disable
      HOST: 0.0.0.0
      PORT: "8080"
      # logging config
      LOG_ENABLED: "true"
      LOG_LEVEL: "info"
      LOG_FORMAT: "json"
      LOG_HTTP: "true"
      LOG_REQUEST_ID: "true"
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 5

  app2:
    build: .
    environment:
      DATABASE_URL: postgres://stock:stock@postgres:5432/stock_market?sslmode=disable
      HOST: 0.0.0.0
      PORT: "8080"
      # logging config
      LOG_ENABLED: "true"
      LOG_LEVEL: "info"
      LOG_FORMAT: "json"
      LOG_HTTP: "true"
      LOG_REQUEST_ID: "true"
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 5
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.8
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - ./configs/promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus