services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stock_market
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://stock:stock@postgres:5432/stock_market?sslmode=disable
      HOST: 0.0.0.0
      PORT: "8080"
      # logging config
      LOG_ENABLED: "true"
      LOG_LEVEL: "info"        # debug|info|warn|error
      LOG_FORMAT: "json"       # json|text
      LOG_HTTP: "true"
      LOG_REQUEST_ID: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/app
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"